# Generated by Django 4.2.13 on 2026-07-07 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('cierre_pendiente', 'Cierre Pendiente'), ('aprobacion_porque_pendiente', 'Aprobación de Porqué Pendiente'), ('cambio_responsable_pendiente', 'Cambio de Responsable Pendiente'), ('asignado_responsable', 'Asignado como Responsable'), ('mensaje_urgente', 'Mensaje Urgente')], db_index=True, default='cierre_pendiente', help_text='Notification category for filtering and admin panel display', max_length=50, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='leida',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Leida'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['destinatario', 'tipo', 'leida'], name='notificacio_destina_e3b819_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['tipo'], name='notificacio_tipo_2df5d5_idx'),
        ),
    ]
