# Generated by Django 4.2.13 on 2026-07-07 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '__first__'),
        ('hallazgos', '0002_add_cliente_asociado_to_hallazgo'),
    ]

    operations = [
        migrations.AddField(
            model_name='hallazgo',
            name='sector',
            field=models.ForeignKey(blank=True, help_text='Hallazgo sector classification (RECLAMO_CLIENTE, PROVEEDOR, INTERNO, etc.)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hallazgos', to='catalogos.sectorcatalog', verbose_name='Sector'),
        ),
        migrations.AddField(
            model_name='hallazgo',
            name='subseccion',
            field=models.ForeignKey(blank=True, help_text='Subsection (only for sector=INTERNO)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hallazgos', to='catalogos.subsectioncatalog', verbose_name='Subsección'),
        ),
        migrations.AddField(
            model_name='hallazgo',
            name='tipo_catalogo',
            field=models.ForeignKey(blank=True, help_text='Hallazgo type from dynamic catalog (QUEJA_CLIENTE, NO_CONFORMIDAD, etc.)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hallazgos', to='catalogos.tipocatalog', verbose_name='Tipo (Catalogo)'),
        ),
        migrations.AddIndex(
            model_name='hallazgo',
            index=models.Index(fields=['sector', 'estado'], name='hallazgos_h_sector__859c9b_idx'),
        ),
        migrations.AddIndex(
            model_name='hallazgo',
            index=models.Index(fields=['tipo_catalogo', 'estado'], name='hallazgos_h_tipo_ca_8aa37b_idx'),
        ),
    ]
