# Generated by Django 4.2.13 on 2026-08-12 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hallazgos', '0003_hallazgo_sector_hallazgo_subseccion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HallazgoResponsableHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(verbose_name='Fecha de Asignación')),
                ('fecha_remocion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Remoción')),
                ('hallazgo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsable_historial', to='hallazgos.hallazgo', verbose_name='Hallazgo')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_responsabilidades', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Histórico de Responsable',
                'verbose_name_plural': 'Histórico de Responsables',
                'ordering': ['-fecha_asignacion'],
                'indexes': [models.Index(fields=['hallazgo', 'responsable'], name='hallazgos_h_hallazg_727ff5_idx'), models.Index(fields=['fecha_asignacion'], name='hallazgos_h_fecha_a_ae23db_idx')],
            },
        ),
    ]
