# Generated by Django 4.2.13 on 2026-07-07 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='SectorCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, help_text='Machine-readable sector code (e.g., RECLAMO_CLIENTE, PROVEEDOR, INTERNO)', max_length=50, unique=True)),
                ('nombre', models.CharField(help_text='Human-readable sector name', max_length=100)),
                ('descripcion', models.TextField(blank=True, default='', help_text='Optional description of the sector')),
                ('activo', models.BooleanField(db_index=True, default=True, help_text='If false, sector is hidden from new hallazgo creation but existing records remain')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sector Catalog',
                'verbose_name_plural': 'Sector Catalogs',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='TipoCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, help_text='Machine-readable type code (e.g., QUEJA_CLIENTE, NO_CONFORMIDAD)', max_length=50, unique=True)),
                ('nombre', models.CharField(help_text='Human-readable type name', max_length=100)),
                ('activo', models.BooleanField(db_index=True, default=True, help_text='If false, type is hidden from new hallazgo creation but existing records remain')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Type Catalog',
                'verbose_name_plural': 'Type Catalogs',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='SubsectionCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, help_text='Machine-readable subsection code (e.g., ADMIN, OPERACIONES)', max_length=50)),
                ('nombre', models.CharField(help_text='Human-readable subsection name', max_length=100)),
                ('activo', models.BooleanField(db_index=True, default=True, help_text='If false, subsection is hidden but existing records remain')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sector', models.ForeignKey(help_text='Parent sector for this subsection', on_delete=django.db.models.deletion.CASCADE, to='catalogos.sectorcatalog')),
            ],
            options={
                'verbose_name': 'Subsection Catalog',
                'verbose_name_plural': 'Subsection Catalogs',
                'ordering': ['sector', 'codigo'],
                'unique_together': {('sector', 'codigo')},
            },
        ),
        migrations.AddIndex(
            model_name='sectorcatalog',
            index=models.Index(fields=['codigo', 'activo'], name='catalogos_s_codigo_4c0972_idx'),
        ),
        migrations.AddIndex(
            model_name='sectorcatalog',
            index=models.Index(fields=['activo'], name='catalogos_s_activo_902abf_idx'),
        ),
        migrations.AddIndex(
            model_name='tipocatalog',
            index=models.Index(fields=['codigo', 'activo'], name='catalogos_t_codigo_44b106_idx'),
        ),
        migrations.AddIndex(
            model_name='tipocatalog',
            index=models.Index(fields=['activo'], name='catalogos_t_activo_7859ac_idx'),
        ),
        migrations.AddIndex(
            model_name='subsectioncatalog',
            index=models.Index(fields=['sector', 'codigo'], name='catalogos_s_sector__91f9ca_idx'),
        ),
        migrations.AddIndex(
            model_name='subsectioncatalog',
            index=models.Index(fields=['activo'], name='catalogos_s_activo_026a27_idx'),
        ),
    ]
