# Generated by Django 4.2.13 on 2026-07-07 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tipocatalog',
            new_name='catalogos_t_codigo_f4b313_idx',
            old_name='catalogos_t_codigo_44b106_idx',
        ),
        migrations.RenameIndex(
            model_name='tipocatalog',
            new_name='catalogos_t_activo_a5f392_idx',
            old_name='catalogos_t_activo_7859ac_idx',
        ),
    ]
