# Generated by Django 4.2.13 on 2026-07-07 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_rename_chat_mensaj_chat_id_tiene_u_idx_chat_mensaj_chat_id_c7b317_idx_and_more'),
        ('hallazgos', '0002_add_cliente_asociado_to_hallazgo'),
        ('analisis_cinco_porques', '0001_initial'),
        ('archivos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='hallazgo',
            field=models.ForeignKey(blank=True, help_text='Parent hallazgo (if this file is attached to a hallazgo)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='hallazgos.hallazgo', verbose_name='Hallazgo'),
        ),
        migrations.AddField(
            model_name='archivo',
            name='mensaje',
            field=models.ForeignKey(blank=True, help_text='Parent message (if this file is attached to a chat message)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='chat.mensaje', verbose_name='Mensaje'),
        ),
        migrations.AddField(
            model_name='archivo',
            name='porque',
            field=models.ForeignKey(blank=True, help_text='Parent porqué (if this file is attached to a 5-why analysis)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='analisis_cinco_porques.analisiscincoporques', verbose_name='5-Why Analysis'),
        ),
        migrations.AddIndex(
            model_name='archivo',
            index=models.Index(fields=['hallazgo'], name='archivos_ar_hallazg_6dcda1_idx'),
        ),
        migrations.AddIndex(
            model_name='archivo',
            index=models.Index(fields=['porque'], name='archivos_ar_porque__b88151_idx'),
        ),
        migrations.AddIndex(
            model_name='archivo',
            index=models.Index(fields=['mensaje'], name='archivos_ar_mensaje_406bbf_idx'),
        ),
    ]
