# Generated by Django 4.2.13 on 2026-07-07 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hallazgos', '0002_add_cliente_asociado_to_hallazgo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisCincoPorques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor_tipo', models.CharField(choices=[('admin', 'Admin'), ('responsable', 'Responsable')], help_text='Role of the user who created this porqué (admin or responsable)', max_length=20)),
                ('texto_causa', models.TextField(help_text="Root cause analysis text (the 'why')")),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], db_index=True, default='pendiente', help_text='Approval state: pendiente (awaiting approval), aprobado, rechazado', max_length=20)),
                ('observacion_rechazo', models.TextField(blank=True, default='', help_text='Reason for rejection (if estado=rechazado)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aprobado_por', models.ForeignKey(blank=True, help_text='Admin who approved this porqué (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='porques_aprobados', to=settings.AUTH_USER_MODEL)),
                ('autor', models.ForeignKey(help_text='User who created this porqué', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='porques_creados', to=settings.AUTH_USER_MODEL)),
                ('hallazgo', models.ForeignKey(help_text='Parent hallazgo', on_delete=django.db.models.deletion.CASCADE, related_name='porques', to='hallazgos.hallazgo')),
            ],
            options={
                'verbose_name': '5-Why Analysis',
                'verbose_name_plural': '5-Why Analyses',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['hallazgo', 'estado'], name='analisis_ci_hallazg_370118_idx'), models.Index(fields=['estado'], name='analisis_ci_estado_1b79f1_idx')],
            },
        ),
    ]
