# Generated by Django 4.2.13 on 2026-07-07 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hallazgos', '0003_hallazgo_sector_hallazgo_subseccion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudCambioResponsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('agregar', 'Add Responsable'), ('cambiar', 'Replace Me')], help_text='Type of change: agregar (add new) or cambiar (replace self)', max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pending'), ('aprobada', 'Approved'), ('rechazada', 'Rejected'), ('anulada', 'Cancelled')], db_index=True, default='pendiente', help_text='Current state: pendiente, aprobada, rechazada, anulada', max_length=20)),
                ('observacion_rechazo', models.TextField(blank=True, default='', help_text='Reason for rejection (if estado=rechazada)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aprobado_por', models.ForeignKey(blank=True, help_text='Admin who approved/rejected this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_cambio_aprobadas', to=settings.AUTH_USER_MODEL)),
                ('hallazgo', models.ForeignKey(help_text='Target hallazgo for responsibility change', on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_cambio_responsable', to='hallazgos.hallazgo')),
                ('solicitante', models.ForeignKey(help_text='Responsable requesting the change', on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_cambio_enviadas', to=settings.AUTH_USER_MODEL)),
                ('usuario_propuesto', models.ForeignKey(help_text='User to be added or who will replace the solicitante', on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_cambio_recibidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Responsibility Change Request',
                'verbose_name_plural': 'Responsibility Change Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['hallazgo', 'estado'], name='solicitud_c_hallazg_b9b42e_idx'), models.Index(fields=['solicitante', 'estado'], name='solicitud_c_solicit_5a81c0_idx'), models.Index(fields=['estado'], name='solicitud_c_estado_c4c6e2_idx')],
            },
        ),
    ]
