# Generated by Django 4.2.13 on 2026-07-07 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_mensaje_tiene_urgente'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='mensaje',
            new_name='chat_mensaj_chat_id_c7b317_idx',
            old_name='chat_mensaj_chat_id_tiene_u_idx',
        ),
        migrations.AddIndex(
            model_name='mensaje',
            index=models.Index(fields=['tiene_urgente'], name='chat_mensaj_tiene_u_21a93b_idx'),
        ),
    ]
