# Generated by Django 4.2.13 on 2026-07-07 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hallazgos', '0002_add_cliente_asociado_to_hallazgo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactoExterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(help_text='Company/organization name', max_length=255)),
                ('telefono', models.CharField(help_text='Contact phone number', max_length=20)),
                ('email', models.EmailField(help_text='Contact email address', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hallazgo', models.OneToOneField(help_text='Parent hallazgo (RECLAMO_CLIENTE sector only)', on_delete=django.db.models.deletion.CASCADE, related_name='contacto_externo', to='hallazgos.hallazgo')),
            ],
            options={
                'verbose_name': 'External Contact',
                'verbose_name_plural': 'External Contacts',
            },
        ),
    ]
