# Generated by Django 4.2.13 on 2026-07-07 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archivos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accion',
            name='archivos',
            field=models.ManyToManyField(blank=True, related_name='acciones', to='archivos.archivo', verbose_name='Archivos'),
        ),
        migrations.CreateModel(
            name='SolicitudCierreAccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de solicitud')),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de resolucion')),
                ('observacion', models.TextField(blank=True, default='', verbose_name='Observacion')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('accion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_cierre', to='acciones.accion', verbose_name='Accion')),
                ('administrador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_cierre_resueltas', to=settings.AUTH_USER_MODEL, verbose_name='Administrador')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_cierre_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Solicitud de Cierre de Accion',
                'verbose_name_plural': 'Solicitudes de Cierre de Accion',
            },
        ),
        migrations.AddConstraint(
            model_name='solicitudcierreaccion',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'PENDIENTE')), fields=('accion',), name='unique_solicitud_cierre_pendiente_por_accion'),
        ),
    ]
